package com.sentrix.ai.action.domain;

public enum ActionType {
    REVIEW_TRANSACTION,
    FLAG_TRANSACTION,
    CREATE_INVESTIGATION,
    ADD_INVESTIGATION_NOTE,
    CREATE_SECURITY_INCIDENT,
    ESCALATE_INCIDENT,
    REQUEST_MANUAL_REVIEW,
    REFRESH_CVE_INTELLIGENCE,
    GENERATE_SECURITY_REPORT,
    MARK_EVENT_FOR_REVIEW
}
