import { useEffect, useState } from 'react';
import { ShieldAlert, RefreshCcw } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { EmptyState } from '@/components/ui/empty-state';
import { fetchIncidents } from '@/api/incidents';
import type { SecurityIncident } from '@/types/incidents';
import { Link } from 'react-router-dom';

const Incidents = () => {
  const [loading, setLoading] = useState(false);
  const [incidents, setIncidents] = useState<SecurityIncident[]>([]);
  
  const loadData = async () => {
    setLoading(true);
    try {
      const res = await fetchIncidents(0, 50);
      setIncidents(res.content || []);
    } catch (error: any) {
      toast.error(error.message || "Failed to load incidents");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const getSeverityColor = (sev: string) => {
    switch(sev?.toUpperCase()) {
      case 'CRITICAL': return 'bg-red-500/10 text-red-600 border-red-500/20';
      case 'HIGH': return 'bg-orange-500/10 text-orange-600 border-orange-500/20';
      case 'MEDIUM': return 'bg-yellow-500/10 text-yellow-600 border-yellow-500/20';
      case 'LOW': return 'bg-blue-500/10 text-blue-600 border-blue-500/20';
      default: return 'bg-slate-500/10 text-slate-600 border-slate-500/20';
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground flex items-center gap-3">
            <ShieldAlert className="h-8 w-8 text-primary" />
            Security Incidents
          </h1>
          <p className="text-muted-foreground mt-1">
            Investigate correlated threat cases generated by the Incident Engine.
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={loadData} disabled={loading}>
            <RefreshCcw className={`mr-2 h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
            Refresh
          </Button>
        </div>
      </div>

      <div className="space-y-4">
        {incidents.length === 0 && !loading ? (
          <EmptyState 
            icon={ShieldAlert}
            title="No security incidents detected"
            description="The correlation engine has not identified any cross-boundary threats."
          />
        ) : (
          <div className="grid gap-4">
            {incidents.map(incident => (
              <Card key={incident.id} className="overflow-hidden hover:shadow-md transition-shadow">
                <Link to={`/incidents/${incident.id}`}>
                  <div className="border-l-4 border-primary p-4">
                    <div className="flex justify-between items-start mb-2">
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-lg">{incident.title}</span>
                        <span className={`text-xs px-2 py-1 rounded-full border font-medium ${getSeverityColor(incident.severity)}`}>
                          {incident.severity} (Score: {incident.riskScore}/100)
                        </span>
                      </div>
                      <span className="text-sm text-muted-foreground">{new Date(incident.createdAt).toLocaleString()}</span>
                    </div>
                    <p className="text-sm text-muted-foreground mt-2">{incident.description}</p>
                    
                    <div className="mt-4 pt-4 border-t flex justify-between items-center text-sm">
                      <span className="font-medium text-slate-600">Events Correlated: {incident.events?.length || 0}</span>
                      <span className="font-bold text-primary">View Investigation &rarr;</span>
                    </div>
                  </div>
                </Link>
              </Card>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default Incidents;
